# Copy:   (c) 2023 blurryroots innovation qanat OÜ
# Author: sven freiberg

name: Mac Release

on:
  push:
    branches:
      - 'release/mac'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:    ${{ github.workspace }}
  QT_VERSION:    5.15.2
  QT_ARCH:       gcc_64
  CMAKE_VERSION: '3.16.x'
  PROJECT:       Eddy
  BUILD_TYPE:    Debug
  SHARED_LIBS:   OFF
  MODULE_LIBS:   OFF
  GENERATE_DMG:  TRUE

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: Manage Qt cache
        uses: actions/cache@v3
        id: macos-cache-qt-${{ env.QT_VERSION }}
        with:
          path: |
            ${{ runner.temp }}/Qt/${{ env.QT_VERSION }}
            /usr
          key: ${{ runner.os }}-qt-${{ env.QT_VERSION }}

      - name: Validating Qt cache
        working-directory:  ${{ github.workspace }}
        run: |
            [ -e ${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_ARCH }} ] \
            && ls -lav ${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_ARCH }} \
            || exit 13
        if: steps.macos-cache-qt-${{ env.QT_VERSION }}.outputs.cache-hit == 'true'

      - name: Installing Qt (cached)
        uses: jurplel/install-qt-action@v3
        with:
          version:          ${{ env.QT_VERSION }}
          host:             linux
          target:           desktop
          arch:             ${{ env.QT_ARCH }}
          dir:              ${{ runner.temp }}
          modules:          debug_info
          setup-python:     false
          cache:            false
          cache-key-prefix: ${{ runner.os }}-qt-${{ env.QT_VERSION }}
        if: steps.macos-cache-qt-${{ env.QT_VERSION }}.outputs.cache-hit != 'true'

      - name: Installing cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: ${{ env.CMAKE_VERSION }}

      - name: Checking out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
              
      - name: Staging project
        run: |
          mkdir ${{ env.SOURCE_DIR }}/Staging
          mkdir ${{ env.SOURCE_DIR }}/Packaged
          cmake -B ${{ env.SOURCE_DIR }}/Staging \
            -DQt5_DIR="${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_ARCH }}/lib/cmake/Qt5" \
            -DBUILD_ID="${{ env.GITHUB_SHA }}" \
            -DBUILD_MODULES=${{ env.MODULE_LIBS }} \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DBUILD_SHARED_LIBS=${{ env.SHARED_LIBS }} \
            -DGENERATE_DMG=${{ env.GENERATE_DMG }} \
            ${{ env.SOURCE_DIR }}

      - name: Building project
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cmake --build ${{ env.SOURCE_DIR }}/Staging
              
      - name: Prepare release candidate
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cmake --build ${{ env.SOURCE_DIR }}/Staging --target ${{ env.PROJECT }}_Stage_Candidate
      
      - name: Uploading results
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.PROJECT }}_${{ env.GITHUB_SHA }}_${{ env.BUILD_TYPE }}.dmg
          path: ${{ env.SOURCE_DIR }}/Release/Candidate/${{ env.PROJECT }}.dmg